### ISSUE TITLE
Krayt Dragon not triggering when it is no longer on the board

### ISSUE THREAD

**Issue by danbastin** [SWU-Karabast/SWUOnline#207] opened 2024-07-09 20:23 UTC
Effects that destroy Krayt Dragon do not trigger its damage effect. Easily replicated by targeting Krayt with Kill the Dragon, Rival's Fall, or Avenger. It would also be good to test that Krayt does damage to the correct target when it changes control. The target should be the player who gains control of Krayt dragon being the "opponent" at the time the take control effect was played.

**Comment by VJubert** [comment] 2024-07-09 20:36
Same issues with Saw Gerrera and Bossk unit when the event make him attack & die

**Comment by VJubert** [comment] 2024-07-09 20:38
I think it is because `AllyAbilities.AllyPlayCardAbility` is a bit late in queue effect

**Comment by danbastin** [comment] 2024-07-09 20:49
Yes, I think in general we can find a good way to handle these triggered effects since they have a somewhat awkward timing in that they don't resolve until the triggering effect has fully resolved.

**Comment by OotTheMonk** [comment] 2024-07-11 02:38
I believe this is a duplicate and is fixed now; feel free to reopen if the issue is still occurring! Made two fixes in this code area today.

**Closed by OotTheMonk** 2024-07-11 02:38 UTC
